<a href="https://colab.research.google.com/github/RutikaW1155/Amazon_clone/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [3]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[375, 23, 256, 310], [375, 23, 256, 131], [375, 234, 256, 79], [188, 126, 33, 252, 6], [188, 126, 33, 252, 129], [48, 375, 333, 256, 165], [428, 391, 14, 252]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 375  23 256 310]
 [  0   0   0   0 375  23 256 131]
 [  0   0   0   0 375 234 256  79]
 [  0   0   0 188 126  33 252   6]
 [  0   0   0 188 126  33 252 129]
 [  0   0   0  48 375 333 256 165]
 [  0   0   0   0 428 391  14 252]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (8, 10)                     │           5,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 375,  23, 256, 310], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 846ms/step


array([[-0.02180042,  0.04182473, -0.00834656, -0.0207971 ,  0.00780958,
        -0.0060161 ,  0.04436146,  0.01167438, -0.00446706, -0.03729216],
       [-0.02180042,  0.04182473, -0.00834656, -0.0207971 ,  0.00780958,
        -0.0060161 ,  0.04436146,  0.01167438, -0.00446706, -0.03729216],
       [-0.02180042,  0.04182473, -0.00834656, -0.0207971 ,  0.00780958,
        -0.0060161 ,  0.04436146,  0.01167438, -0.00446706, -0.03729216],
       [-0.02180042,  0.04182473, -0.00834656, -0.0207971 ,  0.00780958,
        -0.0060161 ,  0.04436146,  0.01167438, -0.00446706, -0.03729216],
       [-0.04058349, -0.04064452, -0.04838588,  0.00854764, -0.00840125,
        -0.03834523,  0.00735444, -0.03307313, -0.04758627,  0.03990532],
       [-0.04818207, -0.00506373,  0.03316121, -0.00815218,  0.0460305 ,
         0.03820826, -0.00360178,  0.01043253, -0.00784912,  0.02340355],
       [ 0.03902454,  0.03972964, -0.04387115,  0.01292006, -0.01830083,
         0.01656676, -0.01501939,  0.00081654

In [24]:
print(model.predict(embedded_docs))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 375,  23, 256, 310], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [20]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [25]:
# vacabulary size
voc_size = 1000

In [ ]:
# One Hot represnetation

In [27]:
onehot_repr = [one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[143, 795, 617, 651, 260, 94], [521, 421, 617, 451, 14, 190], [108, 616, 878, 418], [143, 415, 617, 723, 143, 268], [546, 719, 220, 617, 451, 14, 190], [398, 617, 451, 14, 788, 400]]


In [28]:
## pre padding
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 143 795 617 651 260  94]
 [  0   0   0   0 521 421 617 451  14 190]
 [  0   0   0   0   0   0 108 616 878 418]
 [  0   0   0   0 143 415 617 723 143 268]
 [  0   0   0 546 719 220 617 451  14 190]
 [  0   0   0   0 398 617 451  14 788 400]]


In [29]:
dim = 10

In [30]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
embedded_docs[0]

array([  0,   0,   0,   0, 143, 795, 617, 651, 260,  94], dtype=int32)

In [35]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step


array([[ 0.04372502,  0.00071499, -0.01018199,  0.0148783 ,  0.04113623,
        -0.02225219,  0.02874285,  0.02191224,  0.02209392,  0.00028936],
       [ 0.04372502,  0.00071499, -0.01018199,  0.0148783 ,  0.04113623,
        -0.02225219,  0.02874285,  0.02191224,  0.02209392,  0.00028936],
       [ 0.04372502,  0.00071499, -0.01018199,  0.0148783 ,  0.04113623,
        -0.02225219,  0.02874285,  0.02191224,  0.02209392,  0.00028936],
       [ 0.04372502,  0.00071499, -0.01018199,  0.0148783 ,  0.04113623,
        -0.02225219,  0.02874285,  0.02191224,  0.02209392,  0.00028936],
       [ 0.03405062,  0.04380829,  0.04916307,  0.00718689,  0.01282283,
        -0.04187395,  0.02971097,  0.01811293,  0.04434924,  0.0361908 ],
       [ 0.03790391,  0.0411317 ,  0.01937279,  0.01080861, -0.02920845,
         0.03124789,  0.02353985, -0.03466157, -0.04625689, -0.04296143],
       [-0.02608411, -0.01383798, -0.04746577,  0.04726627, -0.01044153,
        -0.04948529,  0.03751272,  0.00336466